import { useTranslation } from 'react-i18next'

type VehicleModels = {
	[key: string]: string[]
}

export const vehicleMakes = [
	'Acura',
	'Alfa Romeo',
	'Aston Martin',
	'Audi',
	'Bentley',
	'BMW',
	'Bugatti',
	'Buick',
	'Cadillac',
	'Chevrolet',
	'Chrysler',
	'Citroen',
	'Dodge',
	'Ferrari',
	'Fiat',
	'Ford',
	'Genesis',
	'GMC',
	'Honda',
	'Hyundai',
	'Infiniti',
	'Jaguar',
	'Jeep',
	'Kia',
	'Koenigsegg',
	'Lamborghini',
	'Land Rover',
	'Lexus',
	'Lincoln',
	'Lotus',
	'Maserati',
	'Mazda',
	'McLaren',
	'Mercedes-Benz',
	'Mini',
	'Mitsubishi',
	'Nissan',
	'Pagani',
	'Peugeot',
	'Porsche',
	'Ram',
	'Rivian',
	'Rolls-Royce',
	'Saab',
	'Subaru',
	'Suzuki',
	'Tesla',
	'Toyota',
	'Volkswagen',
	'Volvo',
	'Other',
]

export const vehicleModels: VehicleModels = {
	'Acura': ['ILX', 'MDX', 'NSX', 'RDX', 'RL', 'RLX', 'TL', 'TLX', 'TSX', 'ZDX'],
	'Alfa Romeo': ['4C', 'Giulia', 'Stelvio', 'GTV', 'Spider', '33 Stradale', '156', '159', '166', 'Brera'],
	'Aston Martin': ['DB11', 'DBS', 'DBX', 'Rapide', 'Valkyrie', 'Vantage', 'Virage', 'One-77', 'Vanquish', 'Lagonda'],
	'Audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8'],
	'Bentley': [
		'Bentayga',
		'Continental GT',
		'Flying Spur',
		'Mulsanne',
		'Azure',
		'Arnage',
		'Brooklands',
		'Bentley 8 Litre',
		'Bentley Mark VI',
		'Bentley R Type',
	],
	'BMW': ['3 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'X6', 'Z3', 'Z4', 'i3'],
	'Bugatti': [
		'Chiron',
		'Veyron',
		'EB110',
		'Divo',
		'Centodieci',
		'La Voiture Noire',
		'Type 57',
		'Type 41',
		'Type 55',
		'Type 57SC Atlantic',
	],
	'Buick': [
		'Encore',
		'Enclave',
		'Regal',
		'LaCrosse',
		'Century',
		'Roadmaster',
		'Park Avenue',
		'LeSabre',
		'Electra',
		'Riviera',
	],
	'Cadillac': ['Escalade', 'CT4', 'CT5', 'XT4', 'XT5', 'XT6', 'CT6', 'ATS', 'CTS', 'XLR'],
	'Chevrolet': [
		'Silverado',
		'Equinox',
		'Tahoe',
		'Suburban',
		'Camaro',
		'Corvette',
		'Impala',
		'Malibu',
		'Traverse',
		'Spark',
	],
	'Chrysler': [
		'300',
		'Pacifica',
		'Voyager',
		'Aspen',
		'PT Cruiser',
		'Crossfire',
		'Concorde',
		'LHS',
		'New Yorker',
		'Imperial',
	],
	'Citroen': ['C3', 'C4', 'C5', 'C1', 'C2', 'C4 Cactus', 'Berlingo', 'Jumpy', 'SpaceTourer', 'DS3'],
	'Dodge': [
		'Charger',
		'Challenger',
		'Durango',
		'Grand Caravan',
		'Journey',
		'Viper',
		'Dart',
		'Avenger',
		'Caliber',
		'Magnum',
	],
	'Ferrari': [
		'488',
		'812 Superfast',
		'SF90 Stradale',
		'Portofino',
		'Roma',
		'F8 Tributo',
		'GTC4Lusso',
		'812 GTS',
		'Monza SP1',
		'Monza SP2',
	],
	'Fiat': ['500', 'Panda', 'Tipo', 'Punto', 'Doblo', '500X', '500L', 'Qubo', '124 Spider', 'Fullback'],
	'Ford': ['F-150', 'Escape', 'Explorer', 'Expedition', 'Mustang', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Bronco'],
	'Genesis': ['G70', 'G80', 'G90'],
	'GMC': ['Sierra', 'Canyon', 'Terrain', 'Yukon', 'Acadia', 'Envoy', 'Jimmy', 'Safari', 'Typhoon', 'Syclone'],
	'Honda': ['Civic', 'Accord', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Fit', 'Insight', 'Passport', 'Ridgeline'],
	'Hyundai': ['Elantra', 'Sonata', 'Accent', 'Tucson', 'Santa Fe', 'Kona', 'Veloster', 'Palisade', 'Ioniq', 'Genesis'],
	'Infiniti': ['Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX70', 'QX80', 'FX35', 'G37'],
	'Jaguar': ['XE', 'XF', 'XJ', 'F-PACE', 'E-PACE', 'I-PACE', 'XK', 'F-TYPE', 'XJ220', 'XJ13'],
	'Jeep': [
		'Wrangler',
		'Cherokee',
		'Grand Cherokee',
		'Renegade',
		'Compass',
		'Gladiator',
		'Commander',
		'Liberty',
		'Patriot',
		'Wagoneer',
	],
	'Kia': ['Optima', 'Sorento', 'Soul', 'Sportage', 'Rio', 'Forte', 'Stinger', 'Telluride', 'Cadenza', 'K900'],
	'Koenigsegg': ['Agera', 'Jesko', 'Regera', 'Gemera', 'CCX', 'One:1', 'Agera RS', 'Ragnarok', 'Quant', 'Agera Final'],
	'Lamborghini': [
		'Huracan',
		'Aventador',
		'Urus',
		'Gallardo',
		'Murcielago',
		'Diablo',
		'Countach',
		'Reventon',
		'Sesto Elemento',
		'Centenario',
	],
	'Land Rover': [
		'Defender',
		'Discovery',
		'Range Rover',
		'Range Rover Sport',
		'Range Rover Velar',
		'Range Rover Evoque',
		'Freelander',
		'Series I',
		'Series II',
		'Series III',
	],
	'Lexus': ['RX', 'ES', 'NX', 'IS', 'LS', 'GX', 'LX', 'RC', 'LC', 'UX'],
	'Lincoln': [
		'Aviator',
		'Continental',
		'Corsair',
		'MKZ',
		'Nautilus',
		'Navigator',
		'Town Car',
		'LS',
		'Mark Series',
		'Zephyr',
	],
	'Lotus': ['Evora', 'Exige', 'Elise', 'Esprit', 'Europa', 'Elan', 'Cortina', 'Super 7', 'Esprit V8', 'Elite'],
	'Maserati': [
		'Ghibli',
		'Quattroporte',
		'Levante',
		'GranTurismo',
		'GranCabrio',
		'Spyder',
		'Karif',
		'Shamal',
		'3200 GT',
		'BiTurbo',
	],
	'Mazda': ['Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-7', 'CX-9', 'MX-5', 'RX-7', 'RX-8'],
	'McLaren': ['570S', '720S', 'Senna', 'P1', '650S', '675LT', 'MP4-12C', 'F1', 'GT', 'Speedtail'],
	'Mercedes-Benz': ['C-Class', 'E-Class', 'S-Class', 'GLA', 'GLC', 'GLE', 'GLS', 'CLA', 'CLS', 'AMG GT'],
	'Mini': [
		'Cooper',
		'Clubman',
		'Countryman',
		'Paceman',
		'Convertible',
		'Coupe',
		'Roadster',
		'John Cooper Works',
		'Electric',
		'JCW GP',
	],
	'Mitsubishi': [
		'Outlander',
		'Eclipse Cross',
		'Outlander Sport',
		'Lancer',
		'Mirage',
		'i-MiEV',
		'3000GT',
		'Galant',
		'Montero',
		'Diamante',
	],
	'Nissan': ['Altima', 'Maxima', 'Sentra', 'Versa', 'Rogue', 'Murano', 'Pathfinder', 'Armada', 'Titan', 'Frontier'],
	'Pagani': [
		'Huayra',
		'Zonda',
		'Cinque',
		'Tricolore',
		'Roadster BC',
		'Imola',
		'R',
		'Huuracan',
		'Uno',
		'Zonda HP Barchetta',
	],
	'Peugeot': ['208', '308', '508', '2008', '3008', '5008', 'Rifter', 'Partner', 'Traveller', 'iOn'],
	'Porsche': ['911', 'Panamera', 'Cayenne', 'Macan', 'Boxster', 'Cayman', 'Taycan', '918 Spyder', 'Carrera GT', '959'],
	'Ram': ['1500', '2500', '3500', '4500', '5500', 'ProMaster', 'ProMaster City', 'Dakota', 'Ramcharger', 'Cargo Van'],
	'Rivian': ['R1T', 'R1S'],
	'Rolls-Royce': [
		'Phantom',
		'Ghost',
		'Wraith',
		'Dawn',
		'Cullinan',
		'Silver Ghost',
		'Silver Cloud',
		'Silver Shadow',
		'Silver Spirit',
		'Silver Wraith',
	],
	'Saab': ['9-3', '9-5', '900', '9000', 'Sonett', '96', '93', '99', '95', '92'],
	'Subaru': ['Outback', 'Forester', 'Crosstrek', 'Legacy', 'Impreza', 'WRX', 'BRZ', 'Ascent', 'Baja', 'SVX'],
	'Suzuki': ['Swift', 'Vitara', 'Jimny', 'SX4', 'Grand Vitara', 'Kizashi', 'Equator', 'X-90', 'XL-7', 'Forenza'],
	'Tesla': [
		'Model S',
		'Model 3',
		'Model X',
		'Model Y',
		'Roadster',
		'Cybertruck',
		'Semi',
		'Model M',
		'Model E',
		'Model B',
	],
	'Toyota': ['Camry', 'Corolla', 'RAV4', 'Highlander', 'Tacoma', 'Sienna', '4Runner', 'Prius', 'Avalon', 'Tundra'],
	'Volkswagen': ['Golf', 'Jetta', 'Passat', 'Tiguan', 'Atlas', 'Arteon', 'Touareg', 'ID.4', 'ID.3', 'Up'],
	'Volvo': ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'XC70', 'C30', 'C70'],
}

export const vehicleColors = [
	'Black',
	'White',
	'Silver',
	'Gray',
	'Red',
	'Blue',
	'Green',
	'Yellow',
	'Orange',
	'Purple',
	'Pink',
	'Gold',
	'Beige',
	'Brown',
	'Other',
]

export const getVehicleMakes = () => {
	const { t } = useTranslation()

	return vehicleMakes.map((make) => ({
		[make]: t(`values.vehicles.vehicleMakes.${make}`),
	}))
}

export const getVehicleModels = () => {
	const { t } = useTranslation()

	const translatedVehicleModels: VehicleModels = {}

	for (const make in vehicleModels) {
		translatedVehicleModels[make] = vehicleModels[make].map((model) =>
			t(`values.vehicles.vehicleModels.${make}.${model}`),
		)
	}

	return translatedVehicleModels
}

export const getVehicleColors = () => {
	const { t } = useTranslation()

	return vehicleColors.map((color) => ({
		[color]: t(`values.vehicles.vehicleColors.${color}`),
	}))
}
