version: '3.8'

services:
  docker-mongo:
    image: mongo
    container_name: docker-mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: always

  docker-postgresql:
    image: postgres
    container_name: docker-postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - '5432:5432'
    networks:
      - default
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s # Check every 5 seconds
      timeout: 5s # Timeout after 5 seconds
      retries: 5 # Retry 5 times
      start_period: 30s # Wait for 30 seconds before starting health checks
    logging:
      driver: json-file
      options:
        max-size: '10m' # Maximum log file size
        max-file: '5' # Maximum number of log files to retain

  docker-pgadmin:
    image: dpage/pgadmin4
    container_name: docker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5050:80'
    depends_on:
      - docker-postgresql

networks:
  default:
    driver: bridge
    name: app-network
    external: true
