export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as ThemeSwitcher } from './theme-swticher/ThemeSwitcher'
export { default as TabsComponent } from './tabs/Tabs'
export { default as DynamicDataTable } from './table/DataTable'
export { default as ActionsMenu } from './actions/ActionsMenu'
